- name: Install Squid proxy server
  hosts: "{{ ip }}"
  remote_user: "{{ user }}"

  tasks:
    - name: Install squid sever
      apt: name=squid

    - name: Configure squid
      template: src="squid.conf.j2" dest=/etc/squid/squid.conf
      register: squid_configuration

    - name: Restart squid
      service: name=squid state=restarted
      when: squid_configuration.changed